### ISSUE TITLE
How to find "where you belong" in web3

### ISSUE THREAD

**Issue by meow-y** [Web3-Conf-India/Proposal-2022#97]
## Description
I want to share my story about finding my own potentials and limits while understanding where I can add values as a beginner in web3 with no experience. I started as a beginner back in September '21 with no experience in web3 or coding to joining two successful hackathon: 
- web3con (won livepeer bounty for killer web3 video streaming app)
- chainlink (successfully submitted project on May 27, 2022)

---

I also became the team lead for a DAO project called [School of Code](https://twitter.com/ddschoolofcode) while being part of the core contributor to the education team and a group for women/non-binary within the DAO called D_D women (https://twitter.com/devdaowomen).

None of this would have happened without [Developer DAO](https://twitter.com/developer_dao) .
---

### Some points that I'm thinking for my talk:

- How I was able to join the DAO 
- How I got support and motivation from the people and made friends
- How the new Education team was formed and how we started learning
- How I became a part of the moderator's team and became deeply involved
- How I found out where I can add values despite of having no experience with anything
- How I got mentored by my DAO friends and gave me constant support despite of having own self doubts
- How I changed as a person from being introverted to being someone who can lead, take initiatives and make decisions for teams

I will highlight my journey and struggles and how I reached to where I am from an absolute beginner with no web3 knowledge to a contributor.

---

1. **What Is Your Target Audience?** 
 anyone in web3 regardless of their skill level and also anyone who wants to start diving into web3 but hesitating if they can find their belonging 

2. **How Much Time Would You Like To Commit?** 
I can dedicate as much time I need for this honestly

3. **What Is The Style of Your Session?** 
30 min Regular Talks

4. **Are You Submitting Alone or With A Team?**
Alone 

My twitter : https://twitter.com/me256ow (you can reach out to me there)

**Comment by Th3lazykid** [comment]
I'm personally excited for this one, hoping for the best. Cheers.

**Comment by meow-y** [comment]
@Th3lazykid thank you. I will try to bring up about the community involvement and how community and diversity is widely accepted within web3 community.

**Comment by Th3lazykid** [comment]
Sweet, I'll vouch for you. 🤞

**Comment by meow-y** [comment]
I will be closing the issue, thank you for your consideration.
